# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/registry.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11pb/registry.proto\x12\npb_autogen\"q\n\x16RegisterServiceRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x13\n\x0b\x63oncurrency\x18\x04 \x01(\x05\x12\x15\n\rreturn_stream\x18\x05 \x01(\x08\"*\n\x17RegisterServiceResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2h\n\x08Registry\x12\\\n\x0fRegisterService\x12\".pb_autogen.RegisterServiceRequest\x1a#.pb_autogen.RegisterServiceResponse\"\x00\x42)Z\'github.com/bnkrr/iinode-demo/pb_autogenb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb.registry_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/bnkrr/iinode-demo/pb_autogen'
  _globals['_REGISTERSERVICEREQUEST']._serialized_start=33
  _globals['_REGISTERSERVICEREQUEST']._serialized_end=146
  _globals['_REGISTERSERVICERESPONSE']._serialized_start=148
  _globals['_REGISTERSERVICERESPONSE']._serialized_end=190
  _globals['_REGISTRY']._serialized_start=192
  _globals['_REGISTRY']._serialized_end=296
# @@protoc_insertion_point(module_scope)
