# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb import service_pb2 as pb_dot_service__pb2


class ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/pb_autogen.Service/Call',
                request_serializer=pb_dot_service__pb2.ServiceCallRequest.SerializeToString,
                response_deserializer=pb_dot_service__pb2.ServiceCallResponse.FromString,
                )
        self.CallStream = channel.unary_stream(
                '/pb_autogen.Service/CallStream',
                request_serializer=pb_dot_service__pb2.ServiceCallRequest.SerializeToString,
                response_deserializer=pb_dot_service__pb2.ServiceCallResponse.FromString,
                )


class ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=pb_dot_service__pb2.ServiceCallRequest.FromString,
                    response_serializer=pb_dot_service__pb2.ServiceCallResponse.SerializeToString,
            ),
            'CallStream': grpc.unary_stream_rpc_method_handler(
                    servicer.CallStream,
                    request_deserializer=pb_dot_service__pb2.ServiceCallRequest.FromString,
                    response_serializer=pb_dot_service__pb2.ServiceCallResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb_autogen.Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb_autogen.Service/Call',
            pb_dot_service__pb2.ServiceCallRequest.SerializeToString,
            pb_dot_service__pb2.ServiceCallResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CallStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/pb_autogen.Service/CallStream',
            pb_dot_service__pb2.ServiceCallRequest.SerializeToString,
            pb_dot_service__pb2.ServiceCallResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
